name: Build

on: push

env:
  PYAPP_VERSION: v0.23.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Build Python distribution
        run: uv build --wheel

      - name: Download PyApp source code
        working-directory: ${{ runner.temp }}
        run: curl -fL "https://github.com/ofek/pyapp/releases/download/$PYAPP_VERSION/source.tar.gz" | tar -xz

      - name: Build PyApp distribution
        working-directory: ${{ runner.temp }}/pyapp-${{ env.PYAPP_VERSION }}
        run: |
          PYAPP_PROJECT_NAME=gpkg \
          PYAPP_PROJECT_PATH=$(find "$GITHUB_WORKSPACE" -type f -name "*.whl") \
          PYAPP_DISTRIBUTION_EMBED=true \
          PYAPP_UV_ENABLED=true \
          cargo build --release

          mv target/release/pyapp gpkg
          tar -cf gpkg.tar.gz gpkg

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: gpkg
          path: ${{ runner.temp }}/pyapp-${{ env.PYAPP_VERSION }}/gpkg.tar.gz
